const ListingsData = [
  {
    title: "Golden Oak Lodge",
    description: "Nestled in the lush forests of Wayanad, the Golden Oak Lodge offers a luxurious escape for nature lovers. Enjoy modern amenities in a serene environment, with stunning views of Kerala's natural beauty. Perfect for a peaceful retreat away from the city.",
    img: {
      url: "https://prod-strg.forestholidays.co.uk/cdn-cgi/image/width=588,quality=85/https://assets.forestholidays.co.uk/damprodblob/assets/siteassets/locations/cornwall/deerpark/accommodation-page/golden-oak/golden_oak_exterior_views_86ac28f6b6.jpg",
      filename: "golden_oak_exterior",
    },
    cost: 500,
    place: "Wayanad",
    country: "India",
    category: "trending",
    owner: "66c0697486b14cfcf9fe9fda",
    geometry: {
      type: "Point",
      coordinates: [76.121432, 11.685357],
    },
  },
  {
    title: "Lovely Breeze Lodge",
    description: "Experience the perfect blend of luxury and nature at Lovely Breeze Lodge, located in the scenic hills of Kodaikanal. This stunning lodge features an outdoor swimming pool, surrounded by breathtaking landscapes. Ideal for travelers seeking relaxation and adventure.",
    img: {
      url: "https://www.ohioluxurylodging.com/wp-content/uploads/cache/2022/04/Lovely-Breeze-Lodge-Outdoor-swimming-pool/1221382464.jpg",
      filename: "lovely_breeze_lodge",
    },
    cost: 600,
    place: "Kodaikanal",
    country: "India",
    category: "trending",
    owner: "66c0695686b14cfcf9fe9fcf",
    geometry: {
      type: "Point",
      coordinates: [77.489187, 10.238114],
    },
  },
  {
    title: "Pybus Point Retreat",
    description: "Set by the tranquil lakes of Nainital, Pybus Point Retreat offers a peaceful escape amidst the natural beauty of Uttarakhand. With panoramic views of the lake and lush surroundings, it's the perfect destination for a relaxing getaway or a romantic retreat.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/28/14/a8/7e/the-beautiful-pybus-point.jpg?w=300&h=300&s=1",
      filename: "pybus_point_retreat",
    },
    cost: 450,
    place: "Nainital",
    country: "India",
    category: "trending",
    owner: "66c0692d86b14cfcf9fe9fc4",
    geometry: {
      type: "Point",
      coordinates: [79.459033, 29.380303],
    },
  },
  {
    title: "Log Cabin Getaway",
    description: "A cozy log cabin nestled in the serene mountains of Shimla, perfect for those seeking tranquility. Surrounded by breathtaking views, this mountain retreat offers the warmth of a cabin stay with all the modern comforts. Ideal for a peaceful escape into nature.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-s/02/28/b2/08/log-cabins.jpg?w=600&h=-1&s=1",
      filename: "log_cabin_getaway",
    },
    cost: 400,
    place: "Shimla",
    country: "India",
    category: "trending",
    owner: "66c0690d86b14cfcf9fe9fb9",
    geometry: {
      type: "Point",
      coordinates: [77.173403, 31.104814],
    },
  },
  {
    title: "River Run Lodge",
    description: "Located along the serene banks of the Ganges, River Run Lodge in Rishikesh offers breathtaking river views and a tranquil environment. A perfect escape for those seeking peace and relaxation, this lodge provides modern amenities amidst natural beauty.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/04/09/18/the-lodge-at-river-run.jpg?w=1200&h=-1&s=1",
      filename: "river_run_lodge",
    },
    cost: 550,
    place: "Rishikesh",
    country: "India",
    category: "trending",
    owner: "66acbaa978db6cc0ff0b4d53",
    geometry: {
      type: "Point",
      coordinates: [78.267959, 30.086927],
    },
  },
  {
    title: "The Porches Estate",
    description: "Experience royal living at The Porches Estate, a luxurious mansion in the heart of Udaipur. This estate combines modern amenities with the charm of traditional Rajasthani architecture. Perfect for a lavish stay filled with grandeur and elegance.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/26/74/30/the-porches.jpg?w=1200&h=-1&s=1",
      filename: "porches_estate",
    },
    cost: 800,
    place: "Udaipur",
    country: "India",
    category: "trending",
    owner: "66c06c8e21603649dfabd576",
    geometry: {
      type: "Point",
      coordinates: [73.712479, 24.585445],
    },
  },
  {
    title: "Harbor House Inn",
    description: "Harbor House Inn in Kochi offers a heritage stay with panoramic views of the harbor. This charming inn combines history and comfort, providing an ideal getaway for those who appreciate culture and scenic beauty. A perfect mix of relaxation and exploration.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/f7/ce/fa/harbor-house-inn.jpg?w=1200&h=-1&s=1",
      filename: "harbor_house_inn",
    },
    cost: 450,
    place: "Kochi",
    country: "India",
    category: "trending",
    owner: "66c0697486b14cfcf9fe9fda",
    geometry: {
      type: "Point",
      coordinates: [76.257742, 9.931233],
    },
  },
  {
    title: "Lodge in the Hills",
    description: "Escape to the hills at this tranquil lodge, offering breathtaking views of the mountains and valleys. Perfect for nature lovers, this lodge provides a peaceful retreat where you can unwind and reconnect with nature, all while enjoying modern comforts.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/8e/a3/f7/access-to-the-lodge-is.jpg?w=1200&h=-1&s=1",
      filename: "lodge_in_the_hills",
    },
    cost: 500,
    place: "Mussoorie",
    country: "India",
    category: "trending",
    owner: "66c0695686b14cfcf9fe9fcf",
    geometry: {
      type: "Point",
      coordinates: [78.064682, 30.459918],
    },
  },
  {
    title: "The Banyan Tree Retreat",
    description: "Located in the peaceful surroundings of Munnar, The Banyan Tree Retreat offers a serene escape amidst tea plantations and lush greenery. This tranquil retreat provides a perfect blend of relaxation and natural beauty, making it an ideal destination for rejuvenation.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/23/f9/d3/a-warm-greeting-awaits.jpg?w=1200&h=-1&s=1",
      filename: "banyan_tree_retreat",
    },
    cost: 600,
    place: "Munnar",
    country: "India",
    category: "trending",
    owner: "66c0692d86b14cfcf9fe9fc4",
    geometry: {
      type: "Point",
      coordinates: [77.062707, 10.089167],
    },
  },
  {
    title: "Ocean Lodge",
    description: "Located on the pristine shores of Goa, the Ocean Lodge offers a tranquil beachfront experience. Enjoy stunning ocean views and the soothing sound of waves, perfect for a peaceful getaway or a romantic retreat. Modern amenities and relaxing surroundings await.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/bc/34/9f/the-ocean-lodge.jpg?w=800&h=-1&s=1",
      filename: "ocean_lodge",
    },
    cost: 700,
    place: "Goa",
    country: "India",
    category: "beaches",
    owner: "66c0697486b14cfcf9fe9fda",
    geometry: {
      type: "Point",
      coordinates: [73.856743, 15.299326],
    },
  },
  {
    title: "Oceanfront Retreat",
    description: "Nestled along the Arabian Sea in Varkala, this Oceanfront Retreat offers direct access to the beach and mesmerizing views of the coastline. Perfect for beach lovers looking for relaxation, this retreat blends natural beauty with modern comfort.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/59/7a/fb/oceanfront-front-lawn.jpg?w=1200&h=-1&s=1",
      filename: "oceanfront_retreat",
    },
    cost: 650,
    place: "Varkala",
    country: "India",
    category: "beaches",
    owner: "66c0695686b14cfcf9fe9fcf",
    geometry: {
      type: "Point",
      coordinates: [76.702276, 8.737917],
    },
  },
  {
    title: "Beach House Haven",
    description: "Experience the beauty of the Andaman Islands at this serene Beach House Haven. With breathtaking views of the crystal-clear waters and lush surroundings, this beach house offers a perfect escape for those seeking tranquility and a close connection to nature.",
    img: {
      url: "https://www.vrbo.com/vacation-ideas/wp-content/uploads/2023/06/florida-beach-house.jpg",
      filename: "beach_house_haven",
    },
    cost: 750,
    place: "Havelock Island",
    country: "India",
    category: "beaches",
    owner: "66c0692d86b14cfcf9fe9fc4",
    geometry: {
      type: "Point",
      coordinates: [93.015896, 12.006343],
    },
  },
  {
    title: "Coastal Bliss Villa",
    description: "Located in the coastal town of Mahabalipuram, Coastal Bliss Villa offers a serene beachside experience. With stunning views of the Bay of Bengal and easy access to historical sites, this villa is perfect for those looking for both relaxation and exploration.",
    img: {
      url: "https://media.vrbo.com/lodging/69000000/68620000/68618500/68618499/248bd192.jpg?impolicy=resizecrop&rw=1200&ra=fit",
      filename: "coastal_bliss_villa",
    },
    cost: 720,
    place: "Mahabalipuram",
    country: "India",
    category: "beaches",
    owner: "66c0690d86b14cfcf9fe9fb9",
    geometry: {
      type: "Point",
      coordinates: [80.191790, 12.620854],
    },
  },
  {
    title: "Sunset Beach House",
    description: "Located in the tranquil town of Alibaug, Sunset Beach House offers spectacular views of the sunset over the Arabian Sea. With private beach access and modern amenities, it's an ideal retreat for a relaxing coastal escape near Mumbai.",
    img: {
      url: "https://media.vrbo.com/lodging/69000000/68620000/68618500/68618499/6bdb24eb.jpg?impolicy=resizecrop&rw=1200&ra=fit",
      filename: "sunset_beach_house",
    },
    cost: 680,
    place: "Alibaug",
    country: "India",
    category: "beaches",
    owner: "66acbaa978db6cc0ff0b4d53",
    geometry: {
      type: "Point",
      coordinates: [72.874245, 18.642080],
    },
  },
  {
    title: "Palm Grove Beach Resort",
    description: "Situated along the picturesque beaches of Kovalam, Palm Grove Beach Resort offers a luxurious stay amidst palm trees and sandy shores. With beautiful sea views and world-class facilities, this resort is perfect for a serene beachside vacation.",
    img: {
      url: "https://assets.cntraveller.in/photos/60ba1a68a1a415b43b10bd30/master/w_1600,c_limit/Screenshot-2020-02-05-at-6.43.13-PM-866x527.jpg",
      filename: "palm_grove_beach_resort",
    },
    cost: 800,
    place: "Kovalam",
    country: "India",
    category: "beaches",
    owner: "66c06c8e21603649dfabd576",
    geometry: {
      type: "Point",
      coordinates: [76.971157, 8.399496],
    },
  },
  {
    title: "Luxury Hillside Mansion",
    description: "This grand mansion located in the hills of Munnar, Kerala, offers stunning views of the surrounding tea plantations. Featuring expansive grounds, opulent interiors, and complete privacy, it's perfect for a luxurious getaway.",
    img: {
      url: "https://www.jamesedition.com/stories/wp-content/uploads/2020/12/1_Israel.jpg",
      filename: "luxury_hillside_mansion",
    },
    cost: 1500,
    place: "Munnar, Idukki",
    country: "India",
    category: "mansion",
    owner: "66c0697486b14cfcf9fe9fda",
    geometry: {
      type: "Point",
      coordinates: [77.059525, 10.088933],
    },
  },
  {
    title: "Palatial Estate Retreat",
    description: "Nestled in the serene landscapes of Coorg, Karnataka, this palatial estate combines elegance with modern amenities. The mansion is surrounded by coffee plantations and offers luxurious comfort with sprawling gardens and private pools.",
    img: {
      url: "https://www.jamesedition.com/stories/wp-content/uploads/2020/12/5_Mallorca.jpg",
      filename: "palatial_estate_retreat",
    },
    cost: 1600,
    place: "Coorg, Karnataka",
    country: "India",
    category: "mansion",
    owner: "66c0695686b14cfcf9fe9fcf",
    geometry: {
      type: "Point",
      coordinates: [75.740083, 12.337152],
    },
  },
  {
    title: "Elegant Heritage Mansion",
    description: "Located in the heart of Udaipur, Rajasthan, this elegant heritage mansion offers a blend of traditional Rajasthani architecture and modern luxury. With breathtaking views of Lake Pichola and royal interiors, it's an unforgettable experience.",
    img: {
      url: "https://www.jamesedition.com/stories/wp-content/uploads/2020/12/7_LA.jpg",
      filename: "elegant_heritage_mansion",
    },
    cost: 1800,
    place: "Udaipur, Rajasthan",
    country: "India",
    category: "mansion",
    owner: "66c0692d86b14cfcf9fe9fc4",
    geometry: {
      type: "Point",
      coordinates: [73.683296, 24.585445],
    },
  },
  {
    title: "Oceanfront Luxury Villa",
    description: "This exquisite oceanfront mansion in Alappuzha, Kerala, offers unmatched luxury with panoramic views of the Arabian Sea. Enjoy private beach access, a rooftop terrace, and lavish interiors perfect for a luxurious coastal escape.",
    img: {
      url: "https://www.jamesedition.com/stories/wp-content/uploads/2020/12/8_Malibu.jpg",
      filename: "oceanfront_luxury_villa",
    },
    cost: 1700,
    place: "Alappuzha, Kerala",
    country: "India",
    category: "mansion",
    owner: "66c0690d86b14cfcf9fe9fb9",
    geometry: {
      type: "Point",
      coordinates: [76.338848, 9.498066],
    },
  },
  {
    title: "Grand Mountain Mansion",
    description: "Set amidst the breathtaking landscapes of Shimla, Himachal Pradesh, this grand mountain mansion offers a peaceful retreat with luxurious amenities. Enjoy expansive views of the Himalayas, cozy interiors, and a private garden.",
    img: {
      url: "https://www.jamesedition.com/stories/wp-content/uploads/2020/12/9_FR.jpg",
      filename: "grand_mountain_mansion",
    },
    cost: 1650,
    place: "Shimla, Himachal Pradesh",
    country: "India",
    category: "mansion",
    owner: "66acbaa978db6cc0ff0b4d53",
    geometry: {
      type: "Point",
      coordinates: [77.173403, 31.104814],
    },
  },
  {
    title: "Lavish Desert Palace",
    description: "Experience the grandeur of the Thar Desert at this lavish palace-style mansion in Jaisalmer, Rajasthan. With intricately carved stone facades, luxurious interiors, and a private courtyard, it's a royal desert retreat.",
    img: {
      url: "https://assets.architecturaldigest.in/photos/669e0dd8d564016728758b9f/16:9/w_1920,c_limit/Untitled%20design%20-%202024-07-22T131414.068.png",
      filename: "lavish_desert_palace",
    },
    cost: 1750,
    place: "Jaisalmer, Rajasthan",
    country: "India",
    category: "mansion",
    owner: "66c06c8e21603649dfabd576",
    geometry: {
      type: "Point",
      coordinates: [70.916462, 26.915748],
    },
  },
  {
    title: "Serene Mountain Escape",
    description: "This beautiful holiday home in Ranikhet, Uttarakhand, offers breathtaking views of the Himalayas. Surrounded by lush greenery, it provides the perfect escape for nature lovers and peace seekers.",
    img: {
      url: "https://www.holidayhometimes.com/wp-content/uploads/2013/06/Ranikhet-holiday-home-1024x682.jpg",
      filename: "serene_mountain_escape",
    },
    cost: 900,
    place: "Ranikhet, Uttarakhand",
    country: "India",
    category: "mountains",
    owner: "66c0697486b14cfcf9fe9fda",
    geometry: {
      type: "Point",
      coordinates: [79.431236, 29.642073],
    },
  },
  {
    title: "Luxury Mountain Retreat",
    description: "Set in the heart of Manali, Himachal Pradesh, this luxury retreat offers modern comforts with stunning mountain views. With spacious interiors and private balconies, it is ideal for a relaxing vacation in the mountains.",
    img: {
      url: "https://www.bestdesignprojects.com/wp-content/uploads/2015/01/Top-10-Mountain-Houses-Around-the-World-4.jpg",
      filename: "luxury_mountain_retreat",
    },
    cost: 1100,
    place: "Manali, Himachal Pradesh",
    country: "India",
    category: "mountains",
    owner: "66c0695686b14cfcf9fe9fcf",
    geometry: {
      type: "Point",
      coordinates: [77.179682, 32.239632],
    },
  },
  {
    title: "Tranquil Mountain Lodge",
    description: "Located in the picturesque town of Gulmarg, Jammu and Kashmir, this tranquil lodge is nestled among pine trees. Enjoy the cozy ambiance and the serene views of the snow-capped mountains from every corner.",
    img: {
      url: "https://www.housedigest.com/img/gallery/30-gorgeous-mountain-houses-you-can-rent-on-airbnb-upgrade/intro-1705680682.webp",
      filename: "tranquil_mountain_lodge",
    },
    cost: 950,
    place: "Gulmarg, Jammu and Kashmir",
    country: "India",
    category: "mountains",
    owner: "66c0692d86b14cfcf9fe9fc4",
    geometry: {
      type: "Point",
      coordinates: [74.380532, 34.048902],
    },
  },
  {
    title: "Rustic Cabin Retreat",
    description: "Escape to this charming cabin in Kodaikanal, Tamil Nadu, surrounded by rolling hills and forests. Perfect for a quiet getaway, this cabin offers a blend of rustic charm and modern amenities.",
    img: {
      url: "https://www.housedigest.com/img/gallery/30-gorgeous-mountain-houses-you-can-rent-on-airbnb-upgrade/luxurious-cabin-in-blairsville-georgia-1705680682.webp",
      filename: "rustic_cabin_retreat",
    },
    cost: 850,
    place: "Kodaikanal, Tamil Nadu",
    country: "India",
    category: "mountains",
    owner: "66c0690d86b14cfcf9fe9fb9",
    geometry: {
      type: "Point",
      coordinates: [77.489218, 10.238113],
    },
  },
  {
    title: "Hilltop Studio Cabin",
    description: "Perched atop the hills of Lonavala, Maharashtra, this studio cabin offers panoramic views of the Sahyadri mountains. The cozy interiors and serene atmosphere make it a perfect retreat for a peaceful getaway.",
    img: {
      url: "https://www.housedigest.com/img/gallery/30-gorgeous-mountain-houses-you-can-rent-on-airbnb-upgrade/studio-cabin-in-gatlinburg-tennessee-1705680682.webp",
      filename: "hilltop_studio_cabin",
    },
    cost: 900,
    place: "Lonavala, Maharashtra",
    country: "India",
    category: "mountains",
    owner: "66acbaa978db6cc0ff0b4d53",
    geometry: {
      type: "Point",
      coordinates: [73.409487, 18.755793],
    },
  },
  {
    title: "Vineyard Cottage in the Hills",
    description: "This vineyard cottage in the hills of Ooty, Tamil Nadu, is a perfect blend of luxury and nature. Surrounded by lush vineyards and misty mountains, it's an idyllic spot for a serene holiday.",
    img: {
      url: "https://www.housedigest.com/img/gallery/30-gorgeous-mountain-houses-you-can-rent-on-airbnb-upgrade/the-vineyard-cottage-in-jonesville-north-carolina-1705680682.webp",
      filename: "vineyard_cottage_hills",
    },
    cost: 1000,
    place: "Ooty, Tamil Nadu",
    country: "India",
    category: "mountains",
    owner: "66c06c8e21603649dfabd576",
    geometry: {
      type: "Point",
      coordinates: [76.693096, 11.406414],
    },
  },
  {
    title: "Cozy Room in Delhi",
    description: "This cozy and well-furnished room in South Delhi offers a comfortable stay with all modern amenities. Ideal for solo travelers or couples, it's located near popular attractions and shopping areas.",
    img: {
      url: "https://images.oyoroomscdn.com/uploads/hotel_image/40695/large/tnhhpmqvbgdk.jpg",
      filename: "cozy_room_delhi",
    },
    cost: 400,
    place: "South Delhi, Delhi",
    country: "India",
    category: "rooms",
    owner: "66c0697486b14cfcf9fe9fda",
    geometry: {
      type: "Point",
      coordinates: [77.2090, 28.6139],
    },
  },
  {
    title: "Elegant Room in Jaipur",
    description: "Located in the heart of Jaipur, this elegant room offers a blend of Rajasthani heritage with modern comfort. Enjoy a peaceful stay close to the city's historical monuments and bazaars.",
    img: {
      url: "https://cf.bstatic.com/xdata/images/hotel/max1280x900/586698396.jpg?k=a944476ee3b5edd9660a2d63d074bc52d44c097b26ec7efe0fcc31cdcfc35e48&o=&hp=1",
      filename: "elegant_room_jaipur",
    },
    cost: 500,
    place: "Jaipur, Rajasthan",
    country: "India",
    category: "rooms",
    owner: "66c0695686b14cfcf9fe9fcf",
    geometry: {
      type: "Point",
      coordinates: [75.7873, 26.9124],
    },
  },
  {
    title: "Modern Room in Bengaluru",
    description: "A modern and stylish room in Bengaluru, Karnataka, equipped with all the necessary amenities for a relaxing stay. Centrally located, it's perfect for business travelers and tourists alike.",
    img: {
      url: "https://cf.bstatic.com/xdata/images/hotel/max1280x900/586698390.jpg?k=a3e588fb3e456e3f84d0820cf9b2b6d6a41cb06a44db472619cc09c021a0ee46&o=&hp=1",
      filename: "modern_room_bengaluru",
    },
    cost: 450,
    place: "Bengaluru, Karnataka",
    country: "India",
    category: "rooms",
    owner: "66c0692d86b14cfcf9fe9fc4",
    geometry: {
      type: "Point",
      coordinates: [77.5946, 12.9716],
    },
  },
  {
    title: "Luxury Room in Mumbai",
    description: "This luxury room in Mumbai, Maharashtra, offers a premium stay with high-end amenities and a stunning city view. Located in a prime area, it's close to the city's major landmarks and attractions.",
    img: {
      url: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/585268302.jpg?k=720fc37bddd54ae7632223a4c6406c33cdb2e78b153169d032b9c83c0d978bb6&o=&hp=1",
      filename: "luxury_room_mumbai",
    },
    cost: 600,
    place: "Mumbai, Maharashtra",
    country: "India",
    category: "rooms",
    owner: "66c0690d86b14cfcf9fe9fb9",
    geometry: {
      type: "Point",
      coordinates: [72.8777, 19.0760],
    },
  },
  {
    title: "Rajasthani Castle Retreat",
    description: "Experience royal living in this Rajasthani castle retreat located in the heart of Jaipur. With stunning architecture and luxurious interiors, this palace provides a majestic stay fit for royalty.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/d3/a8/57/images-30-largejpg.jpg?w=700&h=-1&s=1",
      filename: "rajasthani_castle_jaipur",
    },
    cost: 2000,
    place: "Jaipur, Rajasthan",
    country: "India",
    category: "castles",
    owner: "66acbaa978db6cc0ff0b4d53",
    geometry: {
      type: "Point",
      coordinates: [75.7873, 26.9124],
    },
  },
  {
    title: "Elegant Palace Stay",
    description: "Step into history with a stay in this elegant palace in Udaipur. Surrounded by serene lakes and lush gardens, this castle offers an opulent experience with a taste of traditional Rajasthani culture.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/40/63/77/the-palace-after-the.jpg?w=1100&h=-1&s=1",
      filename: "elegant_palace_udaipur",
    },
    cost: 2500,
    place: "Udaipur, Rajasthan",
    country: "India",
    category: "castles",
    owner: "66c06c8e21603649dfabd576",
    geometry: {
      type: "Point",
      coordinates: [73.6823, 24.5710],
    },
  },
  {
    title: "Luxurious Palace in Mysore",
    description: "This luxurious palace in Mysore offers an unforgettable stay with its grand architecture and exquisite interiors. Enjoy the royal treatment and explore the cultural heritage of this historic city.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/52/24/3b/lukshmi-vilas-palace.jpg?w=800&h=-1&s=1",
      filename: "luxurious_palace_mysore",
    },
    cost: 1800,
    place: "Mysore, Karnataka",
    country: "India",
    category: "castles",
    owner: "66c0697486b14cfcf9fe9fda",
    geometry: {
      type: "Point",
      coordinates: [76.6394, 12.2958],
    },
  },
  {
    title: "Vijay Vilas Palace",
    description: "Discover the grandeur of Vijay Vilas Palace in Gujarat. With its stunning blend of Rajput and Mughal architecture, this palace offers an exquisite stay amidst sprawling gardens and tranquil surroundings.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/7a/a8/95/shareiq-1350378355-186155.jpg?w=1000&h=-1&s=1",
      filename: "vijay_vilas_palace_gujarat",
    },
    cost: 2200,
    place: "Gandhinagar, Gujarat",
    country: "India",
    category: "castles",
    owner: "66c0695686b14cfcf9fe9fcf",
    geometry: {
      type: "Point",
      coordinates: [73.2101, 23.2156],
    },
  },
  {
    title: "Historic Fort in Rajasthan",
    description: "Experience history at this majestic fort in Rajasthan. With its traditional decor and panoramic views of the desert, this fort offers a unique and luxurious stay amidst a rich cultural backdrop.",
    img: {
      url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/fe/b2/8f/vijay-vilas-palace.jpg?w=1200&h=-1&s=1",
      filename: "historic_fort_rajasthan",
    },
    cost: 1900,
    place: "Jaisalmer, Rajasthan",
    country: "India",
    category: "castles",
    owner: "66c0692d86b14cfcf9fe9fc4",
    geometry: {
      type: "Point",
      coordinates: [70.9083, 26.9157],
    },
  },
  {
    title: "Luxury Poolside Villa in Goa",
    description: "Indulge in luxury with this stunning villa in Goa, featuring a private pool surrounded by lush gardens. Perfect for a relaxing getaway, the villa offers a serene escape with elegant design and top-notch amenities.",
    img: {
      url: "https://img.jamesedition.com/listing_images/2024/02/12/11/47/56/cd546a68-1a06-4308-9609-860945f0fee5/je/1100xxs.jpg",
      filename: "luxury_poolside_villa_goa",
    },
    cost: 3000,
    place: "Goa",
    country: "India",
    category: "pools",
    owner: "66acbaa978db6cc0ff0b4d53",
    geometry: {
      type: "Point",
      coordinates: [73.9876, 15.2993],
    },
  },
  {
    title: "Modern Pool Retreat in Bengaluru",
    description: "This contemporary pool retreat in Bengaluru offers a sleek design with a spacious pool area and modern amenities. Enjoy a stylish and comfortable stay with easy access to the vibrant city life.",
    img: {
      url: "https://img.jamesedition.com/listing_images/2024/07/19/15/10/38/3548aa1b-be41-4cb6-a1b9-37ad2bd7152d/je/1100xxs.jpg",
      filename: "modern_pool_retreat_bengaluru",
    },
    cost: 2200,
    place: "Bengaluru, Karnataka",
    country: "India",
    category: "pools",
    owner: "66c06c8e21603649dfabd576",
    geometry: {
      type: "Point",
      coordinates: [77.5946, 12.9716],
    },
  },
  {
    title: "Elegant Pool Villa in Kerala",
    description: "Experience tranquility in this elegant pool villa located in the picturesque setting of Kerala. With a private pool and stunning views of the surrounding greenery, this villa provides a perfect retreat for relaxation and rejuvenation.",
    img: {
      url: "https://a0.muscache.com/im/pictures/5524945/86757f69_original.jpg?im_w=1200",
      filename: "elegant_pool_villa_kerala",
    },
    cost: 2700,
    place: "Kerala",
    country: "India",
    category: "pools",
    owner: "66c0697486b14cfcf9fe9fda",
    geometry: {
      type: "Point",
      coordinates: [76.6413, 10.8505],
    },
  },
  {
    title: "Chic Poolside Retreat in Mumbai",
    description: "Enjoy a chic poolside experience in this modern retreat located in Mumbai. With stylish interiors and a beautifully designed pool area, this property offers a blend of luxury and comfort right in the heart of the city.",
    img: {
      url: "https://assets.architecturaldigest.in/photos/60083c58d0435267a8df8fdc/master/w_1600,c_limit/Bali-villa-Uluwatu-SAOTA.jpg",
      filename: "chic_poolside_retreat_mumbai",
    },
    cost: 2900,
    place: "Mumbai, Maharashtra",
    country: "India",
    category: "pools",
    owner: "66c0695686b14cfcf9fe9fcf",
    geometry: {
      type: "Point",
      coordinates: [72.8777, 19.0760],
    },
  },
  {
    title: "Bali-inspired Pool Villa in Goa",
    description: "Immerse yourself in a Bali-inspired ambiance with this stunning pool villa in Goa. Featuring a luxurious pool area and exotic decor, this villa provides a tropical retreat perfect for unwinding and enjoying the sun.",
    img: {
      url: "https://assets.architecturaldigest.in/photos/60083c57e6e1f64740189144/master/w_1600,c_limit/Sol-de-Goa-boutique-hotel-14.jpg",
      filename: "bali_inspired_pool_villa_goa",
    },
    cost: 3200,
    place: "Goa",
    country: "India",
    category: "pools",
    owner: "66c0690d86b14cfcf9fe9fb9",
    geometry: {
      type: "Point",
      coordinates: [73.9876, 15.2993],
    },
  },
  {
    title: "Stylish Poolside Stay in Vadodara",
    description: "This stylish poolside property in Vadodara offers modern amenities and a beautifully designed pool area. Ideal for both relaxation and entertaining, it combines contemporary luxury with comfort.",
    img: {
      url: "https://assets.architecturaldigest.in/photos/60083c57a8f839774170432d/master/w_1600,c_limit/Vadodara-bungalow-by-Studio-Yamini_13.jpg",
      filename: "stylish_poolside_stay_vadodara",
    },
    cost: 2100,
    place: "Vadodara, Gujarat",
    country: "India",
    category: "pools",
    owner: "66acbaa978db6cc0ff0b4d53",
    geometry: {
      type: "Point",
      coordinates: [73.1820, 22.3078],
    },
  },
  {
    title: "Contemporary Pool Villa in Pune",
    description: "This contemporary pool villa in Pune offers a blend of modern design and luxury. Enjoy a spacious pool area with elegant furnishings and high-end amenities, making it a perfect spot for relaxation and gatherings.",
    img: {
      url: "https://assets.architecturaldigest.in/photos/60083c57e6e1f64740189144/master/w_1600,c_limit/Sol-de-Goa-boutique-hotel-14.jpg",
      filename: "contemporary_pool_villa_pune",
    },
    cost: 2500,
    place: "Pune, Maharashtra",
    country: "India",
    category: "pools",
    owner: "66c0692d86b14cfcf9fe9fc4",
    geometry: {
      type: "Point",
      coordinates: [73.8567, 18.5204],
    },
  },




];


module.exports={data : ListingsData};